CREATE TABLE alpacas (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    instruction TEXT NOT NULL,
    input TEXT NOT NULL,
    output TEXT NOT NULL
);
